### PR TITLE
assign EXPRESS_GIT_DEFAULTS fix, promisify hooks fix

### PR DESCRIPTION
**Pull request by jakubknejzlik**

### CODE REVIEW

**Comment by jakubknejzlik** [comment]
also if it's possible to make a new version, because I'm using it on distribution and npm publish created /lib folder...and in this case I need to create new npm module to get around this.

**Comment by alxarch** [comment]
I will look into it as soon as I am back from vacation (Tuesday)

**Comment by alxarch** [comment]
Ok added your changes and published 0.6.1. Thanks!

**Comment by jakubknejzlik** [comment]
Thanks, great!

**Pull request merged**
